### ISSUE TITLE
大佬，能不能自定义网址，把网址存书签后，打开就很方便了

### ISSUE THREAD

**Issue by wz969271142** [alley-rs/fluxy#251]
大佬，能不能自定义网址，把网址存书签后，打开就很方便了

**Comment by thep0y** [comment]
自定义网址有什么意义？不打开本程序，有网址你也用不了啊。

**Comment by wz969271142** [comment]
传到局域网另外一台电脑，只需要打开书签就可以啦，不用输入网址啦



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月29日 21:37 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alley-rs/fluxy] 大佬，能不能自定义网址，把网址存书签后，打开就很方便了 (Issue #251) |

自定义网址有什么意义？不打开本程序，有网址你也用不了啊。

**Comment by wz969271142** [comment]
哦哦，好的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月29日 23:43 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alley-rs/fluxy] 大佬，能不能自定义网址，把网址存书签后，打开就很方便了 (Issue #251) |

局域网内电脑或手机的ip地址通常是随机分配，如果固定网址，前提是你会通过路由固定手机或电脑的ip，基于这种情况，我不认为有必要作为本程序的功能。

**Comment by thep0y** [comment]
如果路由器下连接的终端不多，或者大多数终端不会频繁地断连或接入，ip通常比较稳定，理论上你保存书签后也可以用。

**Comment by wz969271142** [comment]
是的，可以，谢啦 链接最后ts=有一串数字会变，我以为每次网址都不一样，刚才试了下，跟后面的数字没关系



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月30日 08:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alley-rs/fluxy] 大佬，能不能自定义网址，把网址存书签后，打开就很方便了 (Issue #251) |

如果路由器下连接的终端不多，或者大多数终端不会频繁地断连或接入，ip通常比较稳定，理论上你保存书签后也可以用。

**Comment by wz969271142** [comment]
send和receive如果能合到一个网页就更方便了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月30日 08:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alley-rs/fluxy] 大佬，能不能自定义网址，把网址存书签后，打开就很方便了 (Issue #251) |

如果路由器下连接的终端不多，或者大多数终端不会频繁地断连或接入，ip通常比较稳定，理论上你保存书签后也可以用。

**Comment by thep0y** [comment]
对扫码来说，发送和接收分开更好，因为桌面端对更容易做出相应的响应。

通过书签访问是不太常见的需求，我暂时不考虑添加相关支持，因为开发分支的代码已经不需要通过此方式访问了。
